version: '3.9'

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-tier
  app:
    depends_on:
      - mysql
    build: ./
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=mysql
    ports:
      - '8081:8081'
    stdin_open: true
    tty: true
    command: bash -c "/wait-for-it.sh -t 0 mysql:3306 -- npm start"
    networks:
      - app-tier

volumes: 
  db:

networks:
  app-tier:
    driver: bridge
